#include <cstdlib>
#include <random>
#include <iostream>
#include <ctime>
#include "Agent.h"
#include "Matrix.h"

using namespace std;

Agent::Agent() {
	srand(time(0));
	position[0] = rand()%100;
	position[1] = rand()%100;
	cout << "Position " << position[0] << "," << position[1] << "\n";
}

Agent::~Agent() {
}

void Agent::move() {
	random_device rd;  //Will be used to obtain a seed for the random number engine
	mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
	uniform_real_distribution<> dis(0.0, 1.0);
	for (int n = 0; n < 10; ++n) {
		//Use dis to transform the random unsigned int generated by gen into a double in [1, 2)
		std::cout << dis(gen) << ' '; //Each call to dis(gen) generates a new random double
	}
	std::cout << '\n';
}

